apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netra.fullname" . }}-redis
  labels:
    app: netra-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netra-redis
  template:
    metadata:
      labels:
        app: netra-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: netra-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
