apiVersion: v2
name: Netra
description: NETRA Enterprise Security Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Pooja Patel
    email: poojaspatel1375@gmail.com
